# geral
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: cuidado

# desenvolvimento
development:
  <<: *default
  database: savelife_development
# qas
test:
  <<: *default
  database: savelife_test

# production

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  url: postgres://rnymxrhexvehlg:e3c2b922cffcff88762743e7ee0c148db08f7985b81dd52b5d87bbd10e9c47c9@ec2-54-228-162-209.eu-west-1.compute.amazonaws.com:5432/d671f05de5gmur
  database: d671f05de5gmur
  username: rnymxrhexvehlg
  password: e3c2b922cffcff88762743e7ee0c148db08f7985b81dd52b5d87bbd10e9c47c9
